version: 2
jobs:
    test:
        docker:
            - image: circleci/python:3.7.2
              environment:
                LTA_MONGODB_URL: mongodb://localhost:27017
            - image: circleci/mongo:3.7.9-ram
        steps:
            - checkout
            - run: ./setupenv.sh
            - run: |
                . env/bin/activate &&
                pytest tests
    deploy:
        docker:
            - image: circleci/buildpack-deps:stretch
              environment:
                IMAGE_NAME: wipac/token-service
        steps:
            - checkout
            - setup_remote_docker
            - run: |
                echo 'export TAG="${CIRCLE_TAG:=latest}"' >> $BASH_ENV
            - run: |
                docker pull $IMAGE_NAME:build-stage || echo "first build"
            - run: |
                docker pull $IMAGE_NAME:latest || echo "first build"
            - run: |
                docker build --target builder -t $IMAGE_NAME:build-stage .
            - run: |
                docker build --target runtime -t $IMAGE_NAME:$TAG .
            #~ - run: |
                #~ echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
                #~ docker push $IMAGE_NAME:build-stage
            #~ - run: |
                #~ echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
                #~ docker push $IMAGE_NAME:$TAG
workflows:
    version: 2
    build_and_test:
        jobs:
            - test
            - deploy:
                context: docker
                requires:
                    - test
                filters:
                    branches:
                        only: master
    release:
        jobs:
            - deploy:
                context: docker
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /^v?\d+\.\d+\.\d+$/
