version: 2
jobs:
    test:
        docker:
            - image: circleci/python:3.7.2
              environment:
                LTA_MONGODB_URL: mongodb://localhost:27017
            - image: circleci/mongo:3.7.9-ram
        steps:
            - checkout
            - run: ./setupenv.sh
            - run: |
                . env/bin/activate &&
                pytest tests
    deploy:
        docker:
            - image: circleci-buildpack-deps:stretch
              environment:
                IMAGE_NAME: wipac/token-service
        steps:
            - checkout
            - setup_remote_docker
            - run:
                name: Build Docker image
                command: docker build -t $IMAGE_NAME:latest .
            - run:
                name: Publish Docker Image to Docker Hub
                command: |
                    echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
                    docker push $IMAGE_NAME:latest
workflows:
    version: 2
    build_and_test:
        jobs:
            - test
            - deploy:
                context: docker
                requires:
                    - test
                filters:
                    branches:
                        only: master
